-- 1. ga_session (已创建，略)
-- CREATE TABLE IF NOT EXISTS ga_session (...);

-- 2. ga_custom_dimension (注意 index 是保留字，这里映射为 dim_index)
CREATE TABLE IF NOT EXISTS ga_custom_dimension (
    uid VARCHAR(255),
    visit_id VARCHAR(255),
    dim_index INT,
    value VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. ga_hit
CREATE TABLE IF NOT EXISTS ga_hit (
    uid VARCHAR(255),
    visit_id VARCHAR(255),
    hit_number INT,
    time INT,
    hour INT,
    minute INT,
    is_interaction BOOLEAN,
    is_entrance BOOLEAN,
    is_exit BOOLEAN,
    referer VARCHAR(1024),
    page_path VARCHAR(1024),
    hostname VARCHAR(255),
    page_title VARCHAR(1024),
    page_search_keyword VARCHAR(255),
    page_search_category VARCHAR(255),
    event_info_category VARCHAR(255),
    event_info_action VARCHAR(255),
    event_info_label VARCHAR(255),
    event_info_value INT,
    type VARCHAR(50),
    transaction_id VARCHAR(255),
    transaction_revenue BIGINT,
    transaction_tax BIGINT,
    transaction_shipping BIGINT,
    affiliation VARCHAR(255),
    currency_code VARCHAR(10),
    local_transaction_revenue BIGINT,
    local_transaction_tax BIGINT,
    local_transaction_shipping BIGINT,
    transaction_coupon VARCHAR(255),
    e_commerce_action_type VARCHAR(10),
    e_commerce_action_step INT,
    e_commerce_action_option VARCHAR(255),
    social_interaction_network VARCHAR(255),
    social_interaction_action VARCHAR(255),
    social_interaction_target VARCHAR(255),
    content_group_unique_views_1 INT,
    content_group_unique_views_2 INT,
    content_group_unique_views_3 INT,
    latency_tracking_page_load_sample INT,
    latency_tracking_page_load_time INT,
    latency_tracking_page_download_time INT,
    latency_tracking_redirection_time INT,
    latency_tracking_server_connection_time INT,
    latency_tracking_server_response_time INT,
    latency_tracking_speed_metrics_sample INT,
    latency_tracking_dom_interactive_time INT,
    latency_tracking_dom_content_loaded_time INT,
    latency_tracking_dom_latency_metrics_sample INT,
    publisher_dfp_revenue BIGINT,
    publisher_dfp_impressions INT,
    publisher_dfp_clicks INT,
    ad_click_gcl_id VARCHAR(255),
    ad_click_campaign_id VARCHAR(255),
    ad_click_ad_group_id VARCHAR(255),
    ad_click_creative_id VARCHAR(255),
    ad_click_criteria_id VARCHAR(255),
    ad_click_page INT,
    ad_click_slot VARCHAR(50),
    ad_click_criteria_parameters VARCHAR(255),
    ad_click_isVideoAd BOOLEAN,
    app_info_name VARCHAR(255),
    app_info_version VARCHAR(50),
    app_info_id VARCHAR(255),
    app_info_installer_id VARCHAR(255),
    app_info_landing_screen_name VARCHAR(255),
    app_info_screen_name VARCHAR(255),
    app_info_screen_depth INT,
    exception_description TEXT,
    exception_is_fatal BOOLEAN
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. ga_total
CREATE TABLE IF NOT EXISTS ga_total (
    uid VARCHAR(255),
    visit_id VARCHAR(255),
    visits INT,
    hits INT,
    pageviews INT,
    time_on_site INT,
    bounces INT,
    transactions INT,
    transaction_revenue BIGINT,
    new_visits INT,
    screen_views INT,
    unique_screen_views INT,
    time_on_screen INT,
    total_transaction_revenue BIGINT,
    session_quality_dim INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. ga_geo_network
CREATE TABLE IF NOT EXISTS ga_geo_network (
    uid VARCHAR(255),
    visit_id VARCHAR(255),
    continent VARCHAR(50),
    sub_continent VARCHAR(50),
    country VARCHAR(50),
    region VARCHAR(100),
    metro VARCHAR(100),
    city VARCHAR(100),
    city_id VARCHAR(50),
    network_domain VARCHAR(100),
    latitude VARCHAR(50),
    longitude VARCHAR(50),
    network_location VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. ga_traffic_source
CREATE TABLE IF NOT EXISTS ga_traffic_source (
    uid VARCHAR(255),
    visit_id VARCHAR(255),
    referral_path VARCHAR(1024),
    campaign VARCHAR(255),
    source VARCHAR(255),
    medium VARCHAR(255),
    keyword VARCHAR(255),
    ad_content VARCHAR(255),
    adwords_click_info_campaign_id VARCHAR(255),
    adwords_click_info_ad_group_id VARCHAR(255),
    adwords_click_info_creative_id VARCHAR(255),
    adwords_click_info_criteria_id VARCHAR(255),
    adwords_click_info_page INT,
    adwords_click_info_slot VARCHAR(50),
    adwords_click_info_criteria_parameters VARCHAR(255),
    adwords_click_info_gcl_id VARCHAR(255),
    adwords_click_info_customer_id VARCHAR(255),
    adwords_click_info_ad_network_type VARCHAR(50),
    adwords_click_info_targetring_criteria VARCHAR(255),
    adwords_click_info_is_video_ad BOOLEAN,
    is_true_direct BOOLEAN,
    campaign_code VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. ga_device
CREATE TABLE IF NOT EXISTS ga_device (
    uid VARCHAR(255),
    visit_id VARCHAR(255),
    browser VARCHAR(50),
    browser_version VARCHAR(50),
    browser_size VARCHAR(50),
    operating_system VARCHAR(50),
    operating_system_version VARCHAR(50),
    is_mobile BOOLEAN,
    mobile_device_branding VARCHAR(100),
    mobile_device_model VARCHAR(100),
    mobile_input_selector VARCHAR(50),
    mobile_device_info VARCHAR(100),
    mobile_device_marketing_name VARCHAR(100),
    flash_version VARCHAR(50),
    java_enabled BOOLEAN,
    language VARCHAR(50),
    screen_colors VARCHAR(50),
    screen_resolution VARCHAR(50),
    device_category VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
